version: "3"

services:
  db:
    build: .docker/postgres
    container_name: wiser-pg
    ports:
      - 5432:5432
    volumes: 
      - .docker/postgres/db:/var/lib/postgresql/data:z
      - /usr/app/node_modules
    restart: always
    tty: true
    environment:
      - POSTGRES_PASSWORD:${TYPEORM_DATABASE}
      - POSTGRES_DB:${TYPEORM_PASSWORD}

  app:
    build: .
    command: sh -c "npm run typeorm migration:run && npm run start:dev"
    container_name: wiser-node
    network_mode: host
    ports:
      - 3000:3000
    volumes:
      - .:/usr/app:z
    depends_on:
      - db
    