version: "3"

services:
  db:
    build: .docker/postgres
    container_name: wiser-pg
    ports:
      - 5432:5432
    volumes: 
      - .docker/postgres/db:/var/lib/postgresql/data:z
      - /usr/app/node_modules
    restart: always
    networks:
    - Wisernet
    tty: true
    env_file:
      - postgres.env

  app:
    build: .
    container_name: wiser-node
    networks:
    - Wisernet
    ports:
      - 3000:3000
    volumes:
      - .:/usr/app:z
    depends_on:
      - db
    
networks:
  Wisernet:
      driver: bridge
      ipam:
          driver: default
          config:
              - subnet: "192.168.0.0/24"
                gateway: "192.168.0.1"